### ISSUE TITLE
Fix: tick() not declared in this scope

### ISSUE THREAD

**Issue by az6667** [Reflowster/Reflowster_Reflow#1]
within displayMenu(), there is:

while(1) {
tick();

Compile error indicates tick() is not declared in this scope.
This resolves the error.

while(1) {
reflowster.tick();

**Comment by julianh2o** [comment]
That call to tick actually refers to the tick function on line 445. It's a bit confusing because multiple modules have tick methods. In this case, we want to make sure that we're running the overheat protection while the menu is running.. just in case something weird is going on. (eg. the relay has been switched on manually)

The `reflowster.tick()` method is being called by interrupt and doesn't need to be called by non-interrupt code.

It's possible that the error you're seeing is caused by a failure of ctags to preprocess the file. You can try moving the tick function on line 445 up to the top of the file (or further up) to see if it resolves the issue for you.

**Comment by az6667** [comment]
Then the compile error must have been some crusty Arduino preferences.
Threw out the old bathwater and now it's compiling fine. Thanks!
